dist: trusty
sudo: required

language: node_js

node_js: stable

services:
  - docker

before_script:
  - cp .env.travis .env
  - docker-compose up -d

script:
- docker-compose exec app mocha -r jscoverage -R spec test/test-pages.js
#- docker-compose exec app istanbul cover ./node_modules/mocha/bin/_mocha -- -- -u exports -R spec test/test-pages.js
#- docker-compose exec app codecov
