dist: trusty
sudo: required

language: node_js

node_js: stable

services:
  - docker

before_script:
  - cp .env.travis .env
  - docker-compose up -d

script:
- docker-compose exec app mocha test/test-pages.js
- docker-compose exec app istanbul cover ./node_modules/mocha/bin/_mocha test/*.js -- --require babel-register
#- docker-compose exec app ./node_modules/.bin/nyc --reporter=text mocha
#- docker-compose exec app codecov
