dist: trusty
sudo: required

language: node_js

node_js: stable

services:
    -mongodb

install:
  - npm install
  - npm install mocha chai --save-dev
  - npm install --global mocha
  - npm install request --save-dev

before_script:
  - cp .env.travis .env
  - npm start
  - sleep 15

script:
  - mocha test/unit/test-pages.js
