dist: trusty
sudo: required

language: node_js

node_js: stable

services:
  - docker

before_script:
  - cp .env.travis .env
  - docker-compose up -d

script:
- docker-compose exec app mocha test/test-pages.js --reporter markdown
- docker-compose exec app istanbul cover mocha -- -u exports -R spec test/test-pages.js
#- docker-compose exec app codecov
