dist: trusty
sudo: required

language: node_js

node_js: stable

services:
  - docker

before_script:
  - cp .env.travis .env
  - docker-compose up -d

script:
- docker-compose exec app mocha test/test-pages.js
- docker-compose exec app node ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- test/test-pages.js
#- docker-compose exec app codecov
