dist: trusty
sudo: required

language: node_js

node_js: stable

services:
  - docker

before_script:
  - cp .env.example .env
  - docker-compose up -d

script:
- docker-compose exec app mocha test/unit/test-pages.js
