dist: trusty
sudo: required

language: node_js

node_js: stable

services:
  - docker

before_script:
  - cp .env.travis .env
  - docker-compose up -d

script:
#- docker-compose exec app mocha test/test-pages.js -R spec
- docker-compose exec app nyc --reporter=lcovonly mocha

after_script:
- docker-compose exec app codecov
