version: "3"
services:
  app:
    container_name: app
    restart: always
    build:
     context: ./
     dockerfile: app.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata:
