version: "3"
services:
  app:
    container_name: app
    restart: always
    build:
     context: ./
     dockerfile: app.dockerfile
    ports:
      - "3000:3000"
    environment:
      - "DB_PORT=27017"
      - "DB_HOST=mongo"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=esteban"
      - "MONGO_INITDB_ROOT_PASSWORD=hola1234"
    ports:
      - "27017:27017"
volumes:
  mongodata:
